name: RMan Validation CI - Python Kinematics

on:
  push:
    branches:
      - "python-k"
  pull_request:
    branches:
      - "main"

jobs:
  validate-python:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout from the repository
      uses: actions/checkout@v3
    
    - name: Install python latest
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: List the python's tree and change to it
      run: cd python && tree .

    - name: Install the modules require
      run: python -m pip install -r requirements.txt
    
    - name: Run unittests in kinematics
      run: python -m tests.test_kinematic

    # Adding a step where the project is tested