name: RMan Validation CI - Python Kinematics

on:
  push:
    branches:
      - "python-k"
  pull_request:
    branches:
      - "main"

jobs:
  validate-python:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout from the repository
      uses: actions/checkout@v3
    
    - name: Install python latest
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Run unittests in kinematics
      run: |
        tree python && cd python 
        python -m tests.test_kinematics

    # Adding a step where the project is tested