name: RMan Validation CI - Python Kinematics

on:
  push:
    branches:
      - "python-k"
  pull_request:
    branches:
      - "main"

jobs:
  validate-python:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout from the repository
      uses: actions/checkout@v3
    
    - name: Install python latest
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install and update the modules require
      run: |
        cd python && tree .
        python -m pip install --upgrade setuptools
        python -m pip install --upgrade wheel
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
      # uses: py-actions/py-dependency-install@v3
    
    - name: Run unittests in kinematics
      run: |
        cd python && tree .
        python -m tests.test_kinematic -v

    # Adding a step where the project is tested